version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: npx yarn install
      - run:
          name: Run tests
          command: npx yarn test

  build_release_apk:
    docker:
      - image: cimg/android:2023.02
    working_directory: ~/repo
    environment:
      JDK8_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ANDROID_HOME: /opt/android/sdk
      PATH: /opt/android/sdk/tools:/opt/android/sdk/tools/bin:/opt/android/sdk/platform-tools:$PATH
    steps:
      - checkout
      # - run:
      #     name: Install base64
      #     command: apk add --no-cache coreutils
      - run:
          name: Decode Keystore
          command: |
            echo $ANDROID_KEYSTORE | base64 --decode > my-release-key.keystore
      - run:
          name: Build Release APK
          command: |
            ./gradlew assembleRelease -Pandroid.injected.signing.store.file=my-release-key.keystore \
                                      -Pandroid.injected.signing.store.password=$ANDROID_KEYSTORE_PASSWORD \
                                      -Pandroid.injected.signing.key.alias=$ANDROID_KEY_ALIAS \
                                      -Pandroid.injected.signing.key.password=$ANDROID_KEY_PASSWORD
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_release_apk:
          requires:
            - build
